clusterName: ""
organization: ""

userConfig:
  azure-cloud-controller-manager:
    configMap:
      values: |
        controller:
          azureCredentialFile: /etc/kubernetes/azure.json
          controlPlaneNodeSelector:
            "kubernetes.io/role": null
            "node-role.kubernetes.io/control-plane": '""'
          kubeconfigFromHost: false
  azuredisk-csi-driver:
    configMap:
      values: |
        controller:
          disableAvailabilitySetNodes: false
        linux:
          azure_credential_file: /etc/kubernetes/azure.json
  cilium:
    configMap:
      values: |
        ipam:
          mode: kubernetes
        hubble:
          relay:
            enabled: true
        defaultPolicies:
          enabled: true
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
            - key: CriticalAddonsOnly
              operator: Exists
  coreDNS:
    configMap:
      values: |
        mastersInstance:
          nodeSelector:
            "node-role.kubernetes.io/master": null
            "node-role.kubernetes.io/control-plane": '""'

  external-dns:
    configMap:
      values: |
        flavor: capi
        provider: azure
        clusterID: {{ .Values.clusterName }}
        crd:
          install: false

  # What should we set here ? on Azure we get an hardware clock for chrony ntp
  # By default it uses flatcar ntp endpoints
  # netExporter:
  #   configMap:
  #     values: |
  #       NetExporter:
  #         NTPServers: 169.254.169.123

apps:
  azure-cloud-controller-manager:
    appName: azure-cloud-controller-manager
    chartName: azure-cloud-controller-manager-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/azure-cloud-controller-manager-app
    version: 1.24.6-gs1
  azure-cloud-node-manager:
    appName: azure-cloud-node-manager
    chartName: azure-cloud-node-manager-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/azure-cloud-node-manager-app
    version: 1.24.6-gs1
  azuredisk-csi-driver:
    appName: azuredisk-csi-driver
    chartName: azuredisk-csi-driver-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/azuredisk-csi-driver-app
    version: 1.26.2-gs1
  certExporter:
    appName: cert-exporter
    chartName: cert-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cert-exporter
    version: 2.3.1
  cilium:
    appName: cilium
    chartName: cilium
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cilium-app
    version: 0.6.1
  coreDNS:
    appName: coredns
    chartName: coredns-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/coredns-app
    version: 1.14.2
  external-dns:
    appName: external-dns
    chartName: external-dns-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/external-dns-app
    version: 2.33.0
  kubeStateMetrics:
    appName: kube-state-metrics
    chartName: kube-state-metrics
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/kube-state-metrics-app
    version: 1.14.2
  metricsServer:
    appName: metrics-server
    chartName: metrics-server-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/metrics-server-app
    version: 2.0.0
  netExporter:
    appName: net-exporter
    chartName: net-exporter
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/net-exporter
    version: 1.13.0
  nodeExporter:
    appName: node-exporter
    chartName: node-exporter-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/node-exporter-app
    version: 1.15.0
  observabilityBundle:
    appName: observability-bundle
    chartName: observability-bundle
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    inCluster: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/observability-bundle
    version: 0.2.0
  vpa:
    appName: vertical-pod-autoscaler
    chartName: vertical-pod-autoscaler-app
    catalog: default
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/vertical-pod-autoscaler-app
    version: 3.3.0
  vpaCRD:
    appName: vertical-pod-autoscaler-crd
    chartName: vertical-pod-autoscaler-crd
    catalog: default
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/vertical-pod-autoscaler-crd
    version: 2.0.0
