clusterName: ""
organization: ""

userConfig:
  cilium:
    configMap:
      values: |
        ipam:
          mode: kubernetes
        hubble:
          relay:
            enabled: true
        defaultPolicies:
          enabled: true
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
            - key: CriticalAddonsOnly
              operator: Exists

apps:
  azure-cloud-controller-manager:
    appName: azure-cloud-controller-manager
    chartName: azure-cloud-controller-manager-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/azure-cloud-controller-manager-app
    version: 1.24.5-gs1
  cilium:
    appName: cilium
    chartName: cilium
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cilium-app
    version: 0.6.0
