clusterName: ""
organization: ""

userConfig:
  azure-cloud-controller-manager:
    configMap:
      values: |
        controller:
          azureCredentialFile: /etc/kubernetes/azure.json
          controlPlaneNodeSelector:
            "kubernetes.io/role": null
            "node-role.kubernetes.io/control-plane": '""'
          kubeconfigFromHost: false
  azuredisk-csi-driver:
    configMap:
      values: |
        controller:
          runOnMaster: true
          disableAvailabilitySetNodes: false
          masterNodeSelector:
            "kubernetes.io/role": null
            "node-role.kubernetes.io/control-plane": '""'
        linux:
          azure_credential_file: /etc/kubernetes/azure.json
  cilium:
    configMap:
      values: |
        ipam:
          mode: kubernetes
        hubble:
          relay:
            enabled: true
        defaultPolicies:
          enabled: true
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
            - key: CriticalAddonsOnly
              operator: Exists

apps:
  azure-cloud-controller-manager:
    appName: azure-cloud-controller-manager
    chartName: azure-cloud-controller-manager-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/azure-cloud-controller-manager-app
    version: 1.24.6-gs1
  azure-cloud-node-manager:
    appName: azure-cloud-node-manager
    chartName: azure-cloud-node-manager-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/azure-cloud-node-manager-app
    version: 1.24.6-gs1
  azuredisk-csi-driver:
    appName: azuredisk-csi-driver
    chartName: azuredisk-csi-driver-app
    catalog: default-test
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/azuredisk-csi-driver-app
    version: 1.25.1-gs1-1ac9721f1dd11ce06e018d4d4fe36d6534cb6913
  cilium:
    appName: cilium
    chartName: cilium
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cilium-app
    version: 0.6.0
  coreDNS:
    appName: coredns
    chartName: coredns-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/coredns-app
    version: 1.12.0
