clusterName: ""
organization: ""

userConfig:
  cilium:
    configMap:
      values: |
        ipam:
          mode: kubernetes

apps:
  azure-cloud-controller-manager:
    appName: azure-cloud-controller-manager
    chartName: azure-cloud-controller-manager-app
    catalog: default-test
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/azure-cloud-controller-manager-app
    version: 1.24.5-gs1-b1bda633ef859a3b9f499e8344e98aec1cc14214
  azure-cloud-node-manager:
    appName: azure-cloud-node-manager
    chartName: azure-cloud-node-manager-app
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/azure-cloud-node-manager-app
    version: 1.24.5-gs1
  cilium:
    appName: cilium
    chartName: cilium
    catalog: default
    clusterValues:
      configMap: true
      secret: false
    forceUpgrade: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/cilium-app
    version: 0.6.0
